export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const GET_SOLD_PRODUCT_SUCCESS = 'GET_SOLD_PRODUCT_SUCCESS';
export const GET_SOLD_PRODUCT_FAIL = 'GET_SOLD_PRODUCT_FAIL';